# For now this just checks that nginx is installed and running
# Later on we might also install a default config file, but this should be reusable between hosts
---
- name: nginx installed
  apt: name=nginx update_cache=yes cache_valid_time=3600 state=latest

- name: nginx conf installed
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: nginx started
  service: name=nginx state=started
